### ISSUE TITLE
Provide JSON Schema draft 7 file as part of schemas

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec-json-schemas#120]
#### Reason/Context
[JSON Schema Draft 7](https://json-schema.org/draft-07/json-schema-release-notes.html) is the JSON Schema version AsyncAPI is compatible with. 
All our schemas are written with such dialect, ergo we specify it through the [$schema](https://json-schema.org/understanding-json-schema/reference/schema.html#id4) field.
We also make references to that same schema when referencing through `$ref`.

As you can notice, we strongly depend on such JSON Schema schema. 
I'm suggesting we include it as part of our schemas collection so any tool can directly load all schemas, including the JSON Schema Draft 7 on their Schema registries so they don't need to fetch it externally.

A recent real use case can be found https://github.com/asyncapi/studio/pull/159, where the JSON Schema Draft 7 should be provided to Monaco editor YAML plugin in order to avoid fetching it through a HTTP Request.

The plan will also include one JSON Schema schema file per version we require, meaning if we ever adopt a newer JSON Schema draft, we will include it as well here.

#### Description
Add a new file into [/schemas](https://github.com/asyncapi/spec-json-schemas/tree/master/schemas) called `json-schema-draft-07.json` with the exact content of http://json-schema.org/draft-07/schema.

**Comment by jonaslagoni** [comment]
Because they are a remote reference they are bundled automatically in the bundled schema https://github.com/jonaslagoni/spec-json-schemas/blob/dd457977ac91599ad6833599f2ea6dc4c92b5a13/schemas/2.3.0.json#L482

**Comment by smoya** [comment]
> Because they are a remote reference they are bundled automatically in the bundled schema https://github.com/jonaslagoni/spec-json-schemas/blob/dd457977ac91599ad6833599f2ea6dc4c92b5a13/schemas/2.3.0.json#L482

Oh I see now! Yeah, then this is gonna be closed by https://github.com/asyncapi/spec-json-schemas/pull/128.
Not sure if you want to close this one or rather add a "Fixes https://github.com/asyncapi/spec-json-schemas/issues/120" statement on your PR (I think it's better).

**Comment by jonaslagoni** [comment]
> Not sure if you want to close this one or rather add a "Fixes #120" statement on your PR (I think it's better).

Already there 😄
