### ISSUE TITLE
Support `security` field at Operation level

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec-json-schemas#147]
#### Reason/Context
Part of https://github.com/asyncapi/spec/pull/584.

#### Description
Support `security` field containing an array of SecurityRequirement at Operation level.

As this is a good candidate to be in `v2.3.0` release, the PR should be created from and targeting `2022-01-release` branch.
Also `2.3.0.json` should be the file where these changes should be added then.

As far as I see, the change we need to do is to add a new field called `security` into the `operation` definition. I think we can copy the one from the `server` found in https://github.com/asyncapi/spec-json-schemas/blob/2022-01-release/schemas/2.3.0.json#L192-L197

**Comment by sekharbans-ebay** [comment]
@smoya  - Please review PR. Thanks so much!

**Comment by magicmatatjahu** [comment]
@derberg Could you close this issue? :)

**Comment by derberg** [comment]
released with https://github.com/asyncapi/spec/releases/tag/v2.4.0
