### ISSUE TITLE
Parameter defines it's own reference property

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#165]
#### Describe the bug
Similar to #164 we have a problem with `parameter` defining it's own reference property: https://github.com/asyncapi/spec-json-schemas/blob/a8a5583c2c90ea660243492abcc809fa342cbb86/schemas/2.3.0.json#L554

#### Expected behavior
Parameters should use:
```json
  "additionalProperties": {
    "oneOf": [{"$ref": "#/definitions/parameter"}, {"$ref": "#/definitions/Reference"}]
  },
```

**Comment by derberg** [comment]
@jonaslagoni just to clarify the scope.

what you mean is basically:
- remove https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/parameter.json#L21
- modify https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/parameters.json#L3 so it looks like https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/servers.json#L4 where `$ref` is `oneOF`

right?

**Comment by jonaslagoni** [comment]
Yep 👍

**Comment by mastdev** [comment]
Hi, I get the message on hacktoberfest.com that the repository is not participating in Hacktoberfest 2022. @derberg Can you please confirm? Thanks

**Comment by derberg** [comment]
@mastdev we definitely are. It was maybe because `hacktoberfest` topic on the repo was missing. But as you can see, proper label is there. You can pick it up. It is a nice learning if you did not know [JSON Schema](https://json-schema.org/) before.
