### ISSUE TITLE
Not validating message payload against accurate schema

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#166]
#### Describe the bug
Currently, we default to our own AsyncAPI Schema Object regardless of what is present in the [Message Object](https://www.asyncapi.com/docs/specifications/v2.3.0#messageObject) `schemaFormat`.

#### Expected behavior
Conditional matching the correct schema format to accurately validate schemas.

**Comment by magicmatatjahu** [comment]
Maybe I don't your problem here, but have in mind that payload in the Message Object is define as "any" type in JSON Schema. Custom parser should handle that payload definition and parse/validate it on the parser side, not JSON Schema side and currently we do it for supported schema formats. I don't see any bug here.

**Comment by jonaslagoni** [comment]
Ahh right! 

Actually just assumed there based on the Schema object present. Should that not be changed? 🤔

**Comment by magicmatatjahu** [comment]
🤷🏼 😄

**Comment by jonaslagoni** [comment]
For example, we could add the following to the Message Object:
```json
        {
          "type": "object",
          "additionalProperties": false,
          ...
          "properties": {
            "schemaFormat": {
              "type": "string"
            },
            ...
            "payload": true,
          },
          "allOf": [
            {
              "if": {
                "properties": {
                  "schemaFormat": {
                    "enum": [
                      "application/vnd.aai.asyncapi;version=2.2.0", 
                      "application/vnd.aai.asyncapi+json;version=2.2.0", 
                      "application/vnd.aai.asyncapi+yaml;version=2.2.0"
                    ]
                  }
                }
              },
              "then": {
                "properties": {
                  "payload": {
                    "$ref": "http://asyncapi.com/definitions/2.3.0/schema.json"
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "schemaFormat": {
                    "enum": [
                      "application/schema+json;version=draft-07", 
                      "application/schema+yaml;version=draft-07"
                    ]
                  }
                }
              },
              "then": {
                "properties": {
                  "payload": {
                    "$ref": "http://json-schema.org/draft-07/schema#"
                  }
                }
              }
            }
          ]
       }
```

**Comment by magicmatatjahu** [comment]
@jonaslagoni But then you will validate that schema in `payload` two times (I have only in mind our parser), one time by `AJV` and second by custom SchemaFormat parser - https://github.com/asyncapi/parser-js/blob/master/lib/asyncapiSchemaFormatParser.js#L23

**Comment by jonaslagoni** [comment]
Guess we can remove that then 😛

**Comment by derberg** [comment]
just to understand, you suggest we do validation through AJV rather than custom schema parser?

**Comment by jonaslagoni** [comment]
> just to understand, you suggest we do validation through AJV rather than custom schema parser?

Basically yes, or at least any other implementations does not have to do anything special in order to validate message payloads as it's part of the core schema documents.

This of course only works for JSON schema formats i.e. not possible to do with protobuf for example.

**Comment by jonaslagoni** [comment]
Still needed.

**Comment by jonaslagoni** [comment]
Another important part here is autocompletion for editors i.e. for studio, where currently there are none. With this change, you would have some some auto-completion where possible 🙂

**Comment by jonaslagoni** [comment]
Already solved in both next-major-spec and master.
