### ISSUE TITLE
Cleaning up how sub schemas are defined with references

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#167]
#### Reason/Context
After https://github.com/asyncapi/spec-json-schemas/pull/128 it would be great to have a consistent way of defining how objects and references are defined.

In my opionion it would be better if for example a Message Object JSON Schema file, ONLY contained the information about how a message can be defined, and not that messages can be defined as both a Reference and a Message Object.

Currently, we defined a Message Object as being:
```json
{
  "oneOf": [
    {
      "$ref": "http://asyncapi.com/definitions/2.3.0/Reference.json"
    },
    {
      ...
    }
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/message.json"
}
```
However, I feel like a Message Object should only be defined as is (without reference)
```json
{
  ...,
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/message.json"
}
```
While the definition of Messages should contain the reference:
```json
{
  "type": "object",
  "additionalProperties": {
    "oneOf": [
      {
        "$ref": "http://asyncapi.com/definitions/2.3.0/Reference.json"
      },
      {
        "$ref": "http://asyncapi.com/definitions/2.3.0/message.json"  
      }
    ]
  },
  "description": "JSON objects describing the messages being consumed and produced by the API.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/messages.json"
}
```

**Comment by derberg** [comment]
sounds good to me, it is all about making the info structure clear in the end

**Comment by derberg** [comment]
@jonaslagoni is this something ya want to continue working on?

**Comment by jonaslagoni** [comment]
I dont have the bandwidth at the moment, we can convert it to a good first issue if you want 🙂

**Comment by derberg** [comment]
@jonaslagoni sure, can you help clarify what is the scope? I'm not 100% sure 😅

**Comment by jonaslagoni** [comment]
The overall scope of this issue would be the following:

Each time a schema defines the object as the following:
```json
{
  "oneOf": [
    {
      "$ref": "http://asyncapi.com/definitions/2.3.0/Reference.json"
    },
    {
      ...
    }
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/message.json"
}
```

it should be transformed to only define what the object is i.e:

```json
{
  ...
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/message.json"
}
```

Those who reference the object would then have to use a union for it's definition:

```json
{
  "type": "object",
  "additionalProperties": {
    "oneOf": [
      {
        "$ref": "http://asyncapi.com/definitions/2.3.0/Reference.json"
      },
      {
        "$ref": "http://asyncapi.com/definitions/2.3.0/message.json"  
      }
    ]
  },
  "description": "JSON objects describing the messages being consumed and produced by the API.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/2.3.0/messages.json"
}
```

Some places already have this structure for example here: https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/operation.json#L13 where traits do not contain anything regarding references but it's the operation that uses the traits which allows the references (https://github.com/asyncapi/spec-json-schemas/issues/273).

I have no overview of how many places this is the case, but for each case, you could define that as a separate task or issue.

**Comment by KeneePatel** [comment]
@jonaslagoni  I am thinking to work on this issue. But just to clarify it further. https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/HTTPSecurityScheme.json#L2 this is one of the problem cases right, and I need to envelope the `oneOf` in `additionalProperties` right ? Correct me if I am wrong.

**Comment by jonaslagoni** [comment]
https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/HTTPSecurityScheme.json#L2 is actually one of those that do not need to change, as it defines exactly what HTTP Security Schema object can be defined as. 

This issue is only about how it's defined with references, for example, take a look at https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/message.json

That schema defines both the message and [reference](https://github.com/asyncapi/spec-json-schemas/blob/52b13da9577f6dd4eaa82d1c4ec21be7e1209370/definitions/2.5.0/message.json#L4). The places where that schema is referenced, for example in the [operation object](https://github.com/asyncapi/spec-json-schemas/blob/52b13da9577f6dd4eaa82d1c4ec21be7e1209370/definitions/2.5.0/operation.json#L71), they need to be changed to the `oneOf` example:

```json
    "message": {
      "oneOf": [
        {
          "$ref": "http://asyncapi.com/definitions/2.5.0/Reference.json"
        },
        {
          "$ref": "http://asyncapi.com/definitions/2.5.0/message.json"  
        }
      ]
    }
```

We don't have a full overview of where exactly this is the case, but if you go case by case and provide a PR per case you find that would be perfect 👌 

Let me know if that clarified it!
