### ISSUE TITLE
Extensions Catalog

### ISSUE THREAD

**Issue by Sihamtahi** [asyncapi/spec-json-schemas#280]
#### Reason/Context
As part of the "MVP integration of extensions catalog with AsyncAPI tools to make extension catalog useful" mentorhsip program, detailed here  https://github.com/asyncapi/extensions-catalog/issues/78.  We would like to add in this repo a part that concerns the description of extensions. In the same way as the bindings and spec. 

#### Description
In brief, An extension enables the description of functionality or protocol related features. Everyone can create their own extensions to give users more freedom on the spec. 

We need to have a JSON Schema  validation. In fact, to enable validation in the parser, we need [JSON Schema for AsyncAPI](https://github.com/asyncapi/spec-json-schemas) to contain JSON Schemas of individual extensions. 

The final objective is to have a catalog of extensions that users can browse and use. Then, as time goes by, we enhance the catalog according to the demands / needs.

**Comment by derberg** [comment]
it is basically about doing what @jonaslagoni does here https://github.com/asyncapi/spec-json-schemas/pull/239
just instead of `binding` folder there will be `extensions` folder with schemas, and these will be referenced in required locations inside the main AsyncAPI JSON Schema
