### ISSUE TITLE
Cannot define channel's parameter as reference

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/spec-json-schemas#296]
#### Describe the bug

As we can see in the Studio:

![image](https://user-images.githubusercontent.com/20404945/207093885-14e0fc81-4a33-455d-b952-d4ae9c20d426.png)

![image](https://user-images.githubusercontent.com/20404945/207094908-f1070798-da69-4198-a557-345d1ff4a8bc.png)

In the channel's parameters we cannot make references.

#### How to Reproduce

Open https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/master/examples/streetlights-kafka.yml and convert to the JSON - right corner of the editor -> `Convert to JSON` and you should see yellow marker under `$ref` used in any channel's parameter (in YAML format you won't see error due to the https://github.com/asyncapi/studio/issues/509 issue).

#### Expected behavior

As a user I can make reference to the channel's parameter without "referencing" errors.

**Comment by magicmatatjahu** [comment]
@derberg 

> I don't get why it shows up without throwing errors that AsyncAPI document doesn't follow the schema.

Seriously you can't handle if I'm missing 😅 Because we don't validate schema before resolving refs, but only after, that's you only see "warnings", not "errors".

> Also, I don't mind 👇🏼 change but honestly see no difference, other than "it looks cleaner"

Check this change: https://github.com/asyncapi/spec-json-schemas/pull/320/files#diff-b94db5fcbf97dcbdb295076705f2ad0e55939493cdf43effbea7ceff9fe5404cR4

I changed it to the `parameters` schema where we have union of ref object and parameter item.

**Comment by derberg** [comment]
> Seriously you can't handle if I'm missing

do you remember my comment about your english from last week 🤣 (super internal joke 😄  )

> Because we don't validate schema before resolving refs, but only after, that's you only see "warnings", not "errors".

ups, forgot 😆 

> Check this change: https://github.com/asyncapi/spec-json-schemas/pull/320/files#diff-b94db5fcbf97dcbdb295076705f2ad0e55939493cdf43effbea7ceff9fe5404cR4
I changed it to the parameters schema where we have union of ref object and parameter item.

I'm showing you `2.5` and you point me to `2.4`.
For 2.5 and 2.6 we already had that done, and `parameters` was union already https://asyncapi.com/definitions/2.5.0/parameters.json

I'm trying to understand the change and the difference.

**Comment by magicmatatjahu** [comment]
I purposely wrote it that way so that you could point out the mistake to me and feel better 😄 

> I'm trying to understand the change and the difference.

I show you changes from `2.4.0` perspective, in `2.5.0` and in `2.6.0` we have this same and that's the problem that in the `channels.[x].parameters` field we use ref to the parameter object not to the parameter**S**. I hope it's clear.

**Comment by magicmatatjahu** [comment]
@derberg There is a definition for `channelItem.parameters` https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/channelItem.json#L13 and check that we cannot use `$ref` here -> in my Pr I changed the object to the `parameters`.
