### ISSUE TITLE
[3.0.0]: Define proper regex/format for `server.host` and `server.pathname` 

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/spec-json-schemas#336]
Now, we use normal `type: string` validation rule for `server.host` and `server.pathname` (in 3.0.0 version). We should add proper format (or create from scratch regex) to make validation more restricted (and better).

**Comment by smoya** [comment]
IMHO this should be discarded for 3.0.0 since using a regex for this means deep testing it accepts all use cases. 
@magicmatatjahu

**Comment by smoya** [comment]
Can we close this one @magicmatatjahu?
