### ISSUE TITLE
Enable reusability of schemas between versions

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#364]
#### Reason/Context
There are specifically 2 schemas we wish to share among all versions.
- avroSchema_v1
- openapiSchema_3_0

To achieve this we need to do the following:
1. Move the common schemas to a common definition folder
2. Adapt the bundler (tools/bundler/index.js) to include these common definitions for all versions.

**Comment by achiverram28** [comment]
I would like to work on this

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, is this issue still un-resolved? Also while going through the `tools/bundler/index.js` file, I found some repetitive spelling mistakes in code comments.

**Comment by jonaslagoni** [comment]
Still a problem yea, feel free to grab it 🤙

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, Just to be clear, I need to first move these files from `definitions/v3.0.0` to a new folder `definitions/common` and then update the `loadDefinitions` function in `tools/bundler/index.js` accordingly?

**Comment by AnimeshKumar923** [comment]
what's the status of this one? @jonaslagoni @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Hi @AnimeshKumar923 I am sorry, I forgot this one. I will complete this in the upcoming week as I am currently on vacation.

**Comment by Shahbaz898414** [comment]
Hi @jonaslagoni, is this issue still unresolved?

**Comment by jonaslagoni** [comment]
@Shahbaz898414 its being worked on yes
