### ISSUE TITLE
Traits can be defined as double arrays in v3

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/spec-json-schemas#369]
#### Describe the bug

I opened this PR https://github.com/asyncapi/spec-json-schemas/pull/339 fixing this issue for v2, and I noticed it still persists in the upcoming version

More on the issue can be found here #273 

cc @derberg @jonaslagoni

**Comment by jonaslagoni** [comment]
https://github.com/asyncapi/spec-json-schemas/pull/342 will fix this for v3 🙂
