### ISSUE TITLE
validate extension with json schema

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/spec-json-schemas#408]
This issue is a part of `AsyncAPImentorship program`  [#78](https://github.com/asyncapi/extensions-catalog/issues/78)

#### Main Objective
As part of the Mentorship program we need to validate the extensions with json schema.
A folder named `extensions` would be added just as bindings are present.

#### Description
#280 
In brief, An extension enables the description of functionality or protocol related features. Everyone can create their own extensions to give users more freedom on the spec.

We need to have a JSON Schema validation. In fact, to enable validation in the parser, we need [JSON Schema for AsyncAPI](https://github.com/asyncapi/spec-json-schemas) to contain JSON Schemas of individual extensions.

The final objective is to have a catalog of extensions that users can browse and use. Then, as time goes by, we enhance the catalog according to the demands / needs.

cc: @derberg

**Comment by derberg** [comment]
do we really need a new issue, the one https://github.com/asyncapi/spec-json-schemas/issues/280 is clear, specifies what will be changed, there were no objections. So I do not see a need for new issue, we just need a PR 😄

**Comment by sambhavgupta0705** [comment]
ok then I am closing this one
