### ISSUE TITLE
Examples are going extinct 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#414]
#### Describe the bug
Because the [examples](https://github.com/asyncapi/spec-json-schemas/pull/394) was applied to v2.6 and not v3, it means that going forward and in v3, examples will no longer be available.

cc @AceTheCreator

**Comment by derberg** [comment]
@jonaslagoni this was intentional from @AceTheCreator to not do it for 3.0 until schema is ready. Thus first 2.6 was done to explore later how it works in IDEs. Afaik he plans to add descriptions and examples for 3.0 once the schema is stable and ready for that

**Comment by jonaslagoni** [comment]
Cool 👍 

Was also just to have an issue about it to ensure it's not forgotten 😄

**Comment by jonaslagoni** [comment]
Solved by https://github.com/asyncapi/spec-json-schemas/pull/425
