### ISSUE TITLE
Security scheme object is not working as per docs

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/spec-json-schemas#444]
#### Describe the bug
I get `Property name is not allowed.yaml-schema: AsyncAPI 3.0.0 schema.(0)` when using `name` parameter in `Security Scheme Object` in v3 spec.

![Screenshot 2023-11-08 at 4 04 20 PM](https://github.com/asyncapi/spec-json-schemas/assets/41781438/5062e98b-4ff0-48bc-976b-b128c0ba295e)

#### How to Reproduce
[Link](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6IDMuMC4wCmluZm86CiAgdGl0bGU6IFNsYWNrIFdlYnNvY2tldCBhbmQgT3BlbkFJIEFQSQogIHZlcnNpb246IDEuMC4wCnNlcnZlcnM6CiAgT3BlbkFJX0hUVFBTOgogICAgaG9zdDogYXBpLm9wZW5haS5jb20KICAgIHByb3RvY29sOiBodHRwcwogICAgc2VjdXJpdHk6CiAgICAgIC0gJHJlZjogJyMvY29tcG9uZW50cy9zZWN1cml0eVNjaGVtZXMvb3BlbkFJJwogIFNsYWNrX1dlYlNvY2tldDoKICAgIGhvc3Q6IHdzcy1wcmltYXJ5LnNsYWNrLmNvbQogICAgcHJvdG9jb2w6IHdzcwogIFNsYWNrX0hUVFBTOgogICAgaG9zdDogIHNsYWNrLmNvbQogICAgcHJvdG9jb2w6IGh0dHBzCmNoYW5uZWxzOgogIFNsYWNrUG9zdE1lc3NhZ2U6CiAgICBiaW5kaW5nczoKICAgICAgaHR0cDoKICAgICAgICBtZXRob2Q6IHBvc3QKICAgIGFkZHJlc3M6IC9hcGkvY2hhdC5wb3N0TWVzc2FnZQogICAgc2VydmVyczoKICAgICAgLSAkcmVmOiAiIy9zZXJ2ZXJzL1NsYWNrX0hUVFBTIgogICAgbWVzc2FnZXM6CiAgICAgIHNsYWNrUmVzcG9uc2U6CiAgICAgICAgJHJlZjogIiMvY29tcG9uZW50cy9tZXNzYWdlcy9zbGFja1Jlc3BvbnNlIgogIE9wZW5BSUNvbXBsZXRpb246CiAgICBiaW5kaW5nczoKICAgICAgaHR0cDoKICAgICAgICBtZXRob2Q6IHBvc3QKICAgIHNlcnZlcnM6CiAgICAgIC0gJHJlZjogIiMvc2VydmVycy9PcGVuQUlfSFRUUFMiCiAgICBhZGRyZXNzOiAvdjEvY2hhdC9jb21wbGV0aW9ucwogICAgbWVzc2FnZXM6CiAgICAgIE9wZW5BSVJlcXVlc3Q6IAogICAgICAgICRyZWY6ICIjL2NvbXBvbmVudHMvbWVzc2FnZXMvT3BlbkFJUmVxdWVzdCIKICBTbGFja0V2ZW50U3RyZWFtOgogICAgc2VydmVyczoKICAgICAgLSAkcmVmOiAiIy9zZXJ2ZXJzL1NsYWNrX1dlYlNvY2tldCIKICAgIGFkZHJlc3M6IC9saW5rLz90aWNrZXQ9e3RpY2tldH0mYXBwX2lkPXthcHBfaWR9CiAgICBwYXJhbWV0ZXJzOgogICAgICB0aWNrZXQ6CiAgICAgICAgZGVmYXVsdDogYTJmMGE0ZTUtY2NlMy00NDIzLWJhYmItMDQ1YzJhYjVhYTUwCiAgICAgIGFwcF9pZDoKICAgICAgICBkZWZhdWx0OiBiMDIxMTJkOTM2NGNiMmZlZThhMGVlMDQ4YTkyMGI4YjRiMDEwM2NiMDNmYWIwMjNiNGUzMGY2ZWUyZWZiOThmCiAgICBtZXNzYWdlczoKICAgICAgU2xhY2tSZWFjdGlvbkFkZGVkOgogICAgICAgICRyZWY6ICIjL2NvbXBvbmVudHMvbWVzc2FnZXMvU2xhY2tSZWFjdGlvbkFkZGVkIgogICAgICBHZW5lcmljRXJyb3JQYXlsb2FkOgogICAgICAgICRyZWY6ICIjL2NvbXBvbmVudHMvbWVzc2FnZXMvR2VuZXJpY0Vycm9yUGF5bG9hZCIKb3BlcmF0aW9uczoKICBzZW50U2xhY2tNZXNzYWdlOgogICAgYWN0aW9uOiBzZW5kCiAgICBjaGFubmVsOgogICAgICAkcmVmOiAiIy9jaGFubmVscy9TbGFja1Bvc3RNZXNzYWdlIgogICAgbWVzc2FnZXM6CiAgICAgIC0gJHJlZjogIiMvY29tcG9uZW50cy9tZXNzYWdlcy9zbGFja1Jlc3BvbnNlIgogIEFja0V2ZW50OgogICAgYWN0aW9uOiBzZW5kCiAgICBjaGFubmVsOgogICAgICAkcmVmOiAiIy9jaGFubmVscy9TbGFja0V2ZW50U3RyZWFtIgogICAgbWVzc2FnZXM6CiAgICAgIC0gJHJlZjogIiMvY29tcG9uZW50cy9tZXNzYWdlcy9zbGFja0Fja0V2ZW50IgogIFNlbmRUb09wZW5BSToKICAgIGFjdGlvbjogc2VuZAogICAgY2hhbm5lbDogCiAgICAgICRyZWY6ICIjL2NoYW5uZWxzL09wZW5BSUNvbXBsZXRpb24iCiAgICBtZXNzYWdlczoKICAgICAgLSAkcmVmOiAiIy9jb21wb25lbnRzL21lc3NhZ2VzL3NsYWNrUmVzcG9uc2UiCiAgUmVjZWl2ZUZyb21PcGVuQUk6CiAgICBhY3Rpb246IHJlY2VpdmUKICAgIGNoYW5uZWw6CiAgICAgICRyZWY6ICIjL2NoYW5uZWxzL09wZW5BSUNvbXBsZXRpb24iCiAgICBtZXNzYWdlczoKICAgICAgLSAkcmVmOiAiIy9jb21wb25lbnRzL21lc3NhZ2VzL09wZW5BSUNvbXBsZXRpb25SZXNwb25zZSIKICAgIHJlcGx5OgogICAgICBjaGFubmVsOgogICAgICAgICRyZWY6ICIjL2NoYW5uZWxzL1NsYWNrUG9zdE1lc3NhZ2UiCiAgSGFuZGxlU2xhY2tSZWFjdGlvbjoKICAgIHJlcGx5OgogICAgICBjaGFubmVsOiAKICAgICAgICAkcmVmOiAiIy9jaGFubmVscy9TbGFja0V2ZW50U3RyZWFtIgogICAgYWN0aW9uOiByZWNlaXZlCiAgICBjaGFubmVsOgogICAgICAkcmVmOiAiIy9jaGFubmVscy9TbGFja0V2ZW50U3RyZWFtIgogICAgbWVzc2FnZXM6CiAgICAgIC0gJHJlZjogIiMvY29tcG9uZW50cy9tZXNzYWdlcy9TbGFja1JlYWN0aW9uQWRkZWQiCiAgICAgIC0gJHJlZjogIiMvY29tcG9uZW50cy9tZXNzYWdlcy9HZW5lcmljRXJyb3JQYXlsb2FkIgpjb21wb25lbnRzOgogIHNlY3VyaXR5U2NoZW1lczoKICAgIG9wZW5BSToKICAgICAgdHlwZTogaHR0cAogICAgICBzY2hlbWU6IGJlYXJlcgogICAgICBuYW1lOiB0b2tlbgogIG1lc3NhZ2VzOgogICAgc2xhY2tBY2tFdmVudDoKICAgICAgcGF5bG9hZDoKICAgICAgICB0eXBlOiBvYmplY3QKICAgICAgICBwcm9wZXJ0aWVzOgogICAgICAgICAgZW52ZWxvcGVfaWQ6CiAgICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgc2xhY2tSZXNwb25zZToKICAgICAgcGF5bG9hZDoKICAgICAgICB0eXBlOiBvYmplY3QKICAgICAgICBwcm9wZXJ0aWVzOgogICAgICAgICAgY2hhbm5lbDoKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICB0ZXh0OgogICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgIE9wZW5BSVJlcXVlc3Q6CiAgICAgIHBheWxvYWQ6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICAgICAgcHJvcGVydGllczoKICAgICAgICAgIG1vZGVsOgogICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgZW51bTogWyJncHQtMy41LXR1cmJvIiwgImdwdC0zLjUtdHVyYm8tMTZrIiwgInRleHQtZGF2aW5jaS0wMDIiXQogICAgICAgICAgbWVzc2FnZXM6CiAgICAgICAgICAgIHR5cGU6IGFycmF5CiAgICAgICAgICAgIGl0ZW1zOgogICAgICAgICAgICAgIHR5cGU6IG9iamVjdAogICAgICAgICAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgICAgICAgICByb2xlOgogICAgICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICAgICAgZW51bTogWyJ1c2VyIl0KICAgICAgICAgICAgICAgIGNvbnRlbnQ6CiAgICAgICAgICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAgdGVtcGVyYXR1cmU6CiAgICAgICAgICAgIHR5cGU6IG51bWJlcgogICAgICAgICAgICBtaW5pbXVtOiAwLjAKICAgICAgICAgICAgbWF4aW11bTogMS4wCiAgICAgICAgcmVxdWlyZWQ6CiAgICAgICAgICAtIG1vZGVsCiAgICAgICAgICAtIG1lc3NhZ2VzCiAgICAgICAgICAtIHRlbXBlcmF0dXJlCiAgICBPcGVuQUlDb21wbGV0aW9uUmVzcG9uc2U6CiAgICAgIHBheWxvYWQ6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICAgICAgcHJvcGVydGllczoKICAgICAgICAgIGNob2ljZXM6CiAgICAgICAgICAgIHR5cGU6IGFycmF5CiAgICAgICAgICAgIGl0ZW1zOgogICAgICAgICAgICAgIHR5cGU6IG9iamVjdAogICAgICAgICAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgICAgICAgICBmaW5pc2hfcmVhc29uOgogICAgICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICAgICAgZW51bTogWydzdG9wJ10KICAgICAgICAgICAgICAgIG1lc3NhZ2U6CiAgICAgICAgICAgICAgICAgIHR5cGU6IG9iamVjdAogICAgICAgICAgICAgICAgICBwcm9wZXJ0aWVzOgogICAgICAgICAgICAgICAgICAgIGNvbnRlbnQ6CiAgICAgICAgICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICAgICAgICByb2xlOgogICAgICAgICAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgICAgICAgICAgICBlbnVtOiBbJ2Fzc2lzdGFudCddCiAgICAgICAgICAgICAgcmVxdWlyZWQ6CiAgICAgICAgICAgICAgICAtIGZpbmlzaF9yZWFzb24KICAgICAgICAgICAgICAgIC0gbWVzc2FnZQogICAgICAgIHJlcXVpcmVkOgogICAgICAgICAgLSBjaG9pY2VzCiAgICBTbGFja1JlYWN0aW9uQWRkZWQ6CiAgICAgIHBheWxvYWQ6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICBHZW5lcmljRXJyb3JQYXlsb2FkOgogICAgICBwYXlsb2FkOgogICAgICAgIHR5cGU6IHN0cmluZwp4LXJlbW90ZVNlcnZlcnM6IAogIC0gU2xhY2tfSFRUUFMKICAtIFNsYWNrX1dlYlNvY2tldAogIC0gT3BlbkFJX0hUVFBT) for document in Studio. 

#### Expected behavior
As per [docs](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.15#securitySchemeObject) we should be able to use the `name` parameter in the AsyncAPI document under `Security Scheme Object`.

**Comment by jonaslagoni** [comment]
`name` is only applicable to `type: httpApiKey`: https://www.asyncapi.com/docs/reference/specification/v3.0.0#securitySchemeObject

So the validation is correct.
