### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec-json-schemas#45]
Should we rename this repo to `schemas` or similar? It will not be only for Node.js but for other languages too.

**Comment by derberg** [comment]
`spec-json-schemas`?

**Comment by derberg** [comment]
@fmvilas what do you say about my name proposal?

**Comment by derberg** [comment]
@fmvilas I guess we can rename

just to explain my motivation for `spec-json-schemas`:
- spec relates to spec repo
- json schemas makes it clear it is json schemas, nothing else, unless there might be different in the future? `spec-schemas` ?

**Comment by fmvilas** [comment]
Sorry, I missed your comments above. Whatever makes sense. Just not `asyncapi-node` 👍

**Comment by jonaslagoni** [comment]
I agree it is time to rename this repo, I have to keep reminding myself what the name is... I like `spec-json-schemas` as well 🙂

**Comment by derberg** [comment]
isn't npm package confusing for you too? like this `@asyncapi/specs`

**Comment by derberg** [comment]
@fmvilas @jonaslagoni so what do you think about the package name? shouldn't it be `@asyncapi/spec-json-schemas` too?

**Comment by fmvilas** [comment]
In my case, `@asyncapi/specs` is not confusing because I'm using it from a development context and if I'm "importing" or "requiring" the spec is because I want the spec version that is machine-readable, not the Markdown one. But that's just my perception.

**Comment by jonaslagoni** [comment]
Same for me, `@asyncapi/specs` makes more sense.

**Comment by derberg** [comment]
sounds good to me, for me package name doesn't matter, can be what we have, just wanted to see how complicated rename will be.

**Comment by derberg** [comment]
repo renamed to `spec-json-schemas`

followup PR https://github.com/asyncapi/spec-json-schemas/pull/83
update in link in contribution guide in spec repo can be done later (cause of auto redirects) so I will do it here in this PR -> https://github.com/asyncapi/spec/pull/577
