### ISSUE TITLE
Add code linting (eslint) as part of CI script

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec-json-schemas#467]
#### Reason/Context
The number of JS files [is growing](https://github.com/asyncapi/spec-json-schemas/pull/452) lately, and I feel it's about time to let all these code pass through a code linter in order to ensure consistency and follow standards, also to find and fix potential bugs.

#### Description

- [ ] Install [eslint](https://www.npmjs.com/package/eslint) package as dev dependency
- [ ] Create `.eslintrc` and `.eslintrcignore` files based on, for example, [parser-js](https://github.com/asyncapi/parser-js/blob/master/.eslintrc). Be aware this project doesn't use TypeScript, so modification of those files might be needed.
- [ ] Add new scripts. `npm lint` and `npm lint:fix` as, for example, [parser-js](https://github.com/asyncapi/parser-js/blob/master/package.json#L36-L37) has.
- [ ] Ensure the linter runs on CI (GitHub actions) on each PR.

**Comment by AnimeshKumar923** [comment]
I would like to work in this issue.

**Comment by smoya** [comment]
> I would like to work in this issue.

Of course! Feel free to create a PR at anytime 🚀

**Comment by Min2who** [comment]
@AnimeshKumar923 can i go ahead with this

**Comment by AnimeshKumar923** [comment]
@smoya I would like to give @Min2who a try for this issue.

@Min2who Please go ahead with this issue :+1:

**Comment by Min2who** [comment]
> @smoya I would like to give @Min2who this issue.
> 
> @Min2who Please go ahead with this issue 👍

thnx @AnimeshKumar923

**Comment by AnimeshKumar923** [comment]
> thnx @AnimeshKumar923

let me know if you encounter any difficulties...

**Comment by Min2who** [comment]
@smoya @AnimeshKumar923 how do i ensure this
![image](https://github.com/asyncapi/spec-json-schemas/assets/127925465/83592f1e-303d-4a09-bc9d-d504fe37b150)

**Comment by AnimeshKumar923** [comment]
> @smoya @AnimeshKumar923 how do i ensure this ![image](https://private-user-images.githubusercontent.com/127925465/291050485-83592f1e-303d-4a09-bc9d-d504fe37b150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDMxNjUsIm5iZiI6MTcwMjgwMjg2NSwicGF0aCI6Ii8xMjc5MjU0NjUvMjkxMDUwNDg1LTgzNTkyZjFlLTMwM2QtNGEwOS1iYzlkLWQ1MDRmZTM3YjE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwODQ3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDYxZGQ3ZWE3YzI2YTFhOWM5MzNhMTljYzc5ZmJkMzk0YjQ1MTI1ZGQwZmFmOGMzYjJmOTRiZTUxYmU0ZGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c4Ci4NuoRFcenzZahvFCbfkioKauHeDD8AdnPK70O50)

About this, @smoya If I rememeber correctly, Lukasz talked about modifying the workflows in `.github` repositories. So should we open a PR modifying the CI in `if-nodejs-pr-testing.yml` file to include the linting?

Because if we modify in this repo, it will later be overwritten. So to make it permanent, we should follow the above said approach. Thoughts? :eyes: 
***
_ref: https://github.com/asyncapi/spec-json-schemas/pull/452#pullrequestreview-1775045082_

**Comment by smoya** [comment]
> > @smoya @AnimeshKumar923 how do i ensure this ![image](https://private-user-images.githubusercontent.com/127925465/291050485-83592f1e-303d-4a09-bc9d-d504fe37b150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDMxNjUsIm5iZiI6MTcwMjgwMjg2NSwicGF0aCI6Ii8xMjc5MjU0NjUvMjkxMDUwNDg1LTgzNTkyZjFlLTMwM2QtNGEwOS1iYzlkLWQ1MDRmZTM3YjE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwODQ3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDYxZGQ3ZWE3YzI2YTFhOWM5MzNhMTljYzc5ZmJkMzk0YjQ1MTI1ZGQwZmFmOGMzYjJmOTRiZTUxYmU0ZGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c4Ci4NuoRFcenzZahvFCbfkioKauHeDD8AdnPK70O50)
> 
> About this, @smoya If I rememeber correctly, Lukasz talked about modifying the workflows in `.github` repositories. So should we open a PR modifying the CI in `if-nodejs-pr-testing.yml` file to include the linting?
> 
> Because if we modify in this repo, it will later be overwritten. So to make it permanent, we should follow the above said approach. Thoughts? :eyes: 
> ***
> _context: https://github.com/asyncapi/spec-json-schemas/pull/452#pullrequestreview-1775045082_

The workflow is already calling the lint script https://github.com/asyncapi/.github/blob/master/.github%2Fworkflows%2Fif-nodejs-pr-testing.yml#L74-L75

**Comment by AnimeshKumar923** [comment]
> The workflow is already calling the lint script https://github.com/asyncapi/.github/blob/master/.github%2Fworkflows%2Fif-nodejs-pr-testing.yml#L74-L75

Okay, then as I can see in #473, it will be executed after merging

**Comment by Min2who** [comment]
thnx @smoya @AnimeshKumar923 for the info
