### ISSUE TITLE
Reduce cognitive complexity in `validate-schemas.js`

### ISSUE THREAD

**Issue by AnimeshKumar923** [asyncapi/spec-json-schemas#482]
- While the development of #452, there were complaints about [cognitive complexity by SonarCloud](https://sonarcloud.io/project/issues?id=asyncapi_asyncapi-node&pullRequest=452&resolved=false&inNewCodePeriod=true)

- We have to address this issue by simplifying the script.

**Comment by Min2who** [comment]
@AnimeshKumar923 i am taking this up.Is it okay or you are working in it?

**Comment by AnimeshKumar923** [comment]
@Min2who yes it's okay, feel free to work upon it. :+1:

**Comment by AnimeshKumar923** [comment]
Any updates? @Min2who

**Comment by Min2who** [comment]
@AnimeshKumar923 i have added the changes that you have mentioned.
please review the pr
