### ISSUE TITLE
AsyncAPI v3 shows warning in Studio and IntelliJ plugin when referencing a json schema

### ISSUE THREAD

**Issue by ignacio-nyt** [asyncapi/spec-json-schemas#494]
### Describe the bug.

AsyncAPI v3 shows warning in Studio and IntelliJ plugin when referencing a json schema file. The actual AsyncAPI document is rendered correctly but the warning in the editor persists.

### Expected behavior

AsyncAPI v3 should be able to reference external json schema files without warnings.

### Screenshots

![image (6)](https://github.com/asyncapi/spec-json-schemas/assets/89947202/6a17d68c-2cb7-40e3-bc41-fbdff2233a53)
![image (5)](https://github.com/asyncapi/spec-json-schemas/assets/89947202/ee7b31b9-66a3-4ee6-80c5-86a83862582f)

### How to Reproduce

1. I first created a valid JSON schema
2. I then created an AsyncAPI v3 doc referencing a JSON schema 
4. Then I see the AsyncAPIv3 document rendering the JSON schema correctly but still showing warnings

Please rename the attached AsyncAPI v3 doc `test.txt` to `test.yaml`
[test.txt](https://github.com/asyncapi/spec-json-schemas/files/14541883/test.txt)
[invoice_posted.schema.json](https://github.com/asyncapi/spec-json-schemas/files/14541885/invoice_posted.schema.json)

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by jonaslagoni** [comment]
I think we have a problem with the JSON Schema files that describe payloads.

Payloads are defined with AnySchema: https://github.com/asyncapi/spec-json-schemas/blob/35ea79055d09bdd319ed816e4ec169a12f0bb7a5/definitions/3.0.0/messageObject.json#L19
AnySchema is defined with either schema or multiFormatSchema: https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/3.0.0/anySchema.json#L8
Schema is basically just JSON Schema: https://github.com/asyncapi/spec-json-schemas/blob/35ea79055d09bdd319ed816e4ec169a12f0bb7a5/definitions/3.0.0/schema.json#L5
For multiFormatSchema references should work if you dont define a schemaFormat: https://github.com/asyncapi/spec-json-schemas/blob/35ea79055d09bdd319ed816e4ec169a12f0bb7a5/definitions/3.0.0/multiFormatSchema.json#L70
For multiFormatSchema references should work for AsyncAPI Schema formats: https://github.com/asyncapi/spec-json-schemas/blob/35ea79055d09bdd319ed816e4ec169a12f0bb7a5/definitions/3.0.0/multiFormatSchema.json#L122
Same for all the other schema formats.

Looks like this is JUST a problem with AnySchema and Schema not adding reference type 🤔

**Comment by Pakisan** [comment]
@jonaslagoni yo, man, didn't see this thread

I digged into schema and found this - https://github.com/asyncapi/jasyncapi-idea-plugin/issues/49#issuecomment-1987315546

Only ours `schemeFormat` broke validation

**Comment by Pakisan** [comment]
@jonaslagoni we must double check schemas generation

I found missing `deadLetterQueue` in SQS channel binding and fixed reference for `queue`

https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/3.0.0-without-%24id.json#L5622

I created MR with example changes, which must me moved to generator + re-check bindings

I'm sure that more issues with validation will appear soon

**Comment by Pakisan** [comment]
@ignacio-nyt I have checked your specification and no more validation errors

**Comment by ignacio-nyt** [comment]
> @ignacio-nyt I have checked your specification and no more validation errors
> 
> wait for fix from our side

Thank you!
