### ISSUE TITLE
[BUG] unable to access the scheme in go library 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/spec-json-schemas#529]
### Describe the bug.

Unable to get access to the scheme, I get no error but scheme is nil. 

```go
func TestLoadSchemes(t *testing.T) {
	scheme, err := GetScheme("3.0.0")
	t.Log(err)
	t.Log(scheme)
	assert.Nil(t, err)
	assert.NotNil(t, scheme)
}
```
```
=== RUN   TestLoadSchemes
    /Users/postman/Documents/Programs/Asyncapi/parser-go/scheme/scheme_test.go:10: <nil>
    /Users/postman/Documents/Programs/Asyncapi/parser-go/scheme/scheme_test.go:11: []
    /Users/postman/Documents/Programs/Asyncapi/parser-go/scheme/scheme_test.go:13:
                Error Trace:    /Users/postman/Documents/Programs/Asyncapi/parser-go/scheme/scheme_test.go:13
                Error:          Expected value not to be nil.
                Test:           TestLoadSchemes
--- FAIL: TestLoadSchemes (0.00s)
FAIL
FAIL    github.com/Souvikns/parser-go/scheme    0.639s
```

### Expected behavior

Should get scheme as `[]byte` of the given version. 

### Screenshots

![Screenshot 2024-04-22 at 1 01 03 PM](https://github.com/asyncapi/spec-json-schemas/assets/41781438/1f1e9da7-93f0-4372-b74f-9cdc408596e1)

### How to Reproduce

1. First I installed the library using `go get github.com/asyncapi/spec-json-schemas/v4`
2. Wrote a simple function to test the scheme function. 
```go
package main

import (
	"fmt"
	"log"
	scheme "github.com/asyncapi/spec-json-schemas/v2"
)

func main() {
	schema, err := scheme.Get("3.0.0")
	if err != nil {
		log.Fatalf(err.Error())	
	} else {
		fmt.Println(schema)
	}
}
```

3. run the file using `go run main.go`

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by smoya** [comment]
v4 of the package doesn't contain v3 spec schemas.
Please use v6 of the package + update the import paths (to end in `/v6` rather than `/v4`.

**Comment by smoya** [comment]
Closing as you @Souvikns told me it is working now. Please reopen if applies.
