### ISSUE TITLE
Implement extended tests for bindings and AsyncAPI v3.0.0 definitions

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/spec-json-schemas#551]
### Why do we need this improvement?

I have already wrote basic tests for bindings and AsyncAPI v3.0.0 definitions

Now, it's time to tune them up 

I expect next:
- basic scenarios for schema: 
   - empty
   - example
   - without required fields
   - only required fields
   - extended
   - wrongly extended
- basic scenarios for property:
   - string
   - object
   - null
   - number
   - boolean
   - array
- All current misses are described in related discussion - https://github.com/asyncapi/spec-json-schemas/discussions/546

Initial tests are here: https://github.com/asyncapi/spec-json-schemas/pull/540
Related issue, witch schemas new format: https://github.com/asyncapi/spec-json-schemas/pull/549

### How will this change help?

We will be sure that after changes in our schemes nothing will be broken

### How could it be implemented/designed?

Tune up basic tests

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q3`, `bounty/advanced`, `bounty/coding`
First assignment to third-party contributors: [2024-06-21 00:00:00 UTC+12:00](https://time.lol/#2024-06-21T00:00:00+12:00)
End Of Life after: [2024-07-31 23:59:59 UTC-12:00](https://time.lol/#2024-07-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Third-party contributors should [coherently articulate](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365) how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Advanced        |2024-06-15                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |[2024-07-21](https://time.lol/#2024-07-21T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
@Pakisan, please provide the Draft PR.

**Comment by Pakisan** [comment]
@aeworxet https://github.com/asyncapi/spec-json-schemas/pull/540

Few tests left

**Comment by Pakisan** [comment]
> @aeworxet https://github.com/asyncapi/spec-json-schemas/pull/540
> 
> 
> 
> Few tests left

Tagged folks in PR

**Comment by aeworxet** [comment]
Review for PR https://github.com/asyncapi/spec-json-schemas/pull/540 was requested on 2024-07-26, and it is still in progress.

**Comment by aeworxet** [comment]
@pakisan

Do you need more reviews of PR https://github.com/asyncapi/spec-json-schemas/pull/540 or reviews

https://github.com/asyncapi/spec-json-schemas/pull/540#pullrequestreview-2234501910
https://github.com/asyncapi/spec-json-schemas/pull/540#issuecomment-2289641220

have been enough and you already have an understanding of what to do next?

**Comment by aeworxet** [comment]
Responses, critical for technical resolution of this Bounty Issue (**review of the [PR](https://github.com/asyncapi/spec-json-schemas/pull/540)**) were delayed for three periods of three consecutive working days
https://github.com/asyncapi/spec-json-schemas/pull/540#issuecomment-2252385932
https://github.com/asyncapi/spec-json-schemas/pull/540#issuecomment-2289641220

so all remaining target dates of the Bounty Issue's Timeline are extended by four calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Advanced        |2024-06-15                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)**        |[2024-08-18](https://time.lol/#2024-08-18T23:59:59-12:00)         |[2024-09-08](https://time.lol/#2024-09-08T23:59:59-12:00)         |**[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by Pakisan** [comment]
https://github.com/asyncapi/spec-json-schemas/pull/540 contains both double work result:
- initial tests for our schemes, like info, server, security - that’s how this MR appeared
- extended tests from 551 - by this I added common tests structure with declared requirements like extended, wrongly extended, properties checking and so on

Everything else is out of scope of this issue:
- schemas patching, based on collected typos and errors
- migration to new schema structure, from https://github.com/asyncapi/spec-json-schemas/pull/549

So this Bounty Issue is completed.

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@Pakisan, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty spec-json-schemas#551`, tag `bounty`, and full URL of this Bounty Issue in the description.

**Comment by Pakisan** [comment]
> ### Bounty Issue Is Completed 🎉
> @Pakisan, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty spec-json-schemas#551`, tag `bounty`, and full URL of this Bounty Issue in the description.

Done
