### ISSUE TITLE
Issues with the machine readable file for AsyncAPI 2.0.0

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#81]
**Describe the Issue**
There are some discrepancies with the machine readable version of the AsyncAPI specification version 2.0.0. 

1. on [line 571 ](https://github.com/asyncapi/asyncapi/blob/b5a26229ac14089ad450de41172a546ae8d7a586/versions/2.0.0/schema.json#L571) additionalItems are defined when the schema type is object. 
2. When additionalProperties are indeed allowed on many of the schemas and should follow the patternProperties, how come it is always sat to false 🤔? I.e. on [line 10](https://github.com/asyncapi/asyncapi/blob/b5a26229ac14089ad450de41172a546ae8d7a586/versions/2.0.0/schema.json#L10)
3. On [line 726 ](https://github.com/asyncapi/asyncapi/blob/b5a26229ac14089ad450de41172a546ae8d7a586/versions/2.0.0/schema.json#L726) same as 1.
4. On [line 782](https://github.com/asyncapi/asyncapi/blob/b5a26229ac14089ad450de41172a546ae8d7a586/versions/2.0.0/schema.json#L782) missing `type: [object, array]`.

**Comment by magicmatatjahu** [comment]
I checked issues and they are still valid.

**Comment by derberg** [comment]
@jonaslagoni wanna work on this?

**Comment by derberg** [comment]
There are 2 cases here

#### Case 1

@magicmatatjahu @jonaslagoni 

> On [line 782](https://github.com/asyncapi/asyncapi/blob/b5a26229ac14089ad450de41172a546ae8d7a586/versions/2.0.0/schema.json#L782) missing type: [object, array].

I thought that if there is no type in https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/specificationExtension.json it means that any type is ok. No?

#### Case 2

This one is still valid and very trivial to fix:

One PR related to traits fix: `additionalItems` should be removed from https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/operation.json#L35 and https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/message.json#L157 as in both cases this is an `object`, not an `array`

**Comment by jonaslagoni** [comment]
> I thought that if there is no type in https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/specificationExtension.json it means that any type is ok. No?

Yea you are right, don't know why I suggested it was missing 🧐

**Comment by derberg** [comment]
Final scope for this one 👇🏼 

`additionalItems` should be removed from https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/operation.json#L35 and https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/message.json#L157 as in both cases this is an object, not an array.

And it should be done in all versions, not 2.5 only
