### ISSUE TITLE
Documentation of MessageObject "deprecated" property

### ISSUE THREAD

**Issue by c-pius** [asyncapi/spec-json-schemas#92]
**Describe the bug**

The schema of the MessageObject contains a [deprecated](https://github.com/asyncapi/asyncapi/blob/5ad3a971c82b33717fdec4c8d78173294ae253ff/versions/2.0.0/schema.json#L686) property. This property is not included in the [MessageObject documentation](https://www.asyncapi.com/docs/specifications/2.0.0#messageObject) or the [markdown](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-object). Shouldn't it be though?

**Comment by derberg** [comment]
@KhudaDad414 have a look, I luckily made it stop 😆

**Comment by derberg** [comment]
Also, when fixing can you also improve below message. My bot complains it is not much positive, probably because of `wrong`

![Screenshot 2022-01-13 at 17 19 29](https://user-images.githubusercontent.com/6995927/149367928-42eafc3a-2327-43ca-ac41-58f6b78e0be5.png)
